Repository Esri/hub.js, pull requests merged in 2023-10, with the labels that each got.

#1259 feat: collaborator pane for content workspace
  packages/common/src/content/_internal/ContentBusinessRules.ts
Labels: enhancement

#1270 feat: polishing details pane for site workspace
  packages/common/src/sites/_internal/SiteUiSchemaEdit.ts
  packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts
Labels: enhancement

#1274 feat(hub-common): add section heading for template ui schemas
  packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts
  packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts
Labels: enhancement

#1283 refactor: rows with new calcite text area for details summary
  packages/common/src/content/_internal/ContentUiSchemaEdit.ts
  packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts
  packages/common/src/groups/_internal/GroupUiSchemaEdit.ts
  packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts
  packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts
  packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts
  packages/common/src/pages/_internal/PageUiSchemaEdit.ts
  packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts
  packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
  packages/common/src/sites/_internal/SiteUiSchemaCreate.ts
  packages/common/src/sites/_internal/SiteUiSchemaEdit.ts
  packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts
  packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts
  packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaEdit.test.ts
  packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts
  packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate.test.ts
  packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
  packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts
  packages/common/test/projects/_internal/ProjectUiSchemaCreate.test.ts
  packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
  packages/common/test/sites/_internal/SiteUiSchemaCreate.test.ts
  packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts
  packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts
Labels: refactor

#1294 fix(hub-common): page schema missing _thumbnail; caused details pane to crash
  packages/common/src/pages/_internal/PageSchema.ts
Labels: bug

#1284 feat(hub-common): add support for discussion settings for entities
  package-lock.json
  packages/common/src/core/_internal/getBasePropertyMap.ts
  packages/common/src/core/traits/IWithDiscussions.ts
  packages/common/src/core/traits/IWithEntitySettings.ts
  packages/common/src/core/types/IHubGroup.ts
  packages/common/src/core/updateHubEntity.ts
  packages/common/src/discussions/HubDiscussion.ts
  packages/common/src/discussions/_internal/getPropertyMap.ts
  packages/common/src/discussions/api/settings/getDefaultEntitySettings.ts
  packages/common/src/discussions/api/settings/index.ts
  packages/common/src/discussions/api/types.ts
  packages/common/src/discussions/edit.ts
  packages/common/src/discussions/fetch.ts
  packages/common/test/core/updateHubEntity.test.ts
  packages/common/test/discussions/HubDiscussion.test.ts
  packages/common/test/discussions/api/settings.test.ts
  packages/common/test/discussions/edit.test.ts
  packages/common/test/discussions/fetch.test.ts
  packages/discussions/src/types.ts
Labels: Draft
