Repository Esri/hub.js, pull requests merged in 2023-09, with the labels that each got.

#1204 fix: added default empty quotes for computeProps
  packages/common/src/content/_internal/computeProps.ts
Labels: bug

#1214 feat: partnered orgs added to context
  package-lock.json
  packages/common/src/ArcGISContext.ts
  packages/common/src/ArcGISContextManager.ts
  packages/common/src/types.ts
  packages/common/test/ArcGISContextManager.test.ts
Labels: Stale

#1212 feat: item extent now selectable, savable, and reflects in old and new view
  packages/common/src/content/_internal/computeProps.ts
  packages/common/src/content/edit.ts
  packages/common/src/core/getTypeFromEntity.ts
  packages/common/src/core/schemas/internal/getLocationExtent.ts
  packages/common/src/core/schemas/internal/getLocationOptions.ts
  packages/common/src/extent.ts
  packages/common/test/content/computeProps.test.ts
  packages/common/test/content/edit.test.ts
  packages/common/test/core/schemas/internal/getLocationExtent.test.ts
  packages/common/test/core/schemas/internal/getLocationOptions.test.ts
  packages/common/test/extent/get-geographic-org-extent.test.ts
  packages/common/test/extent/get-org-extent-as-bbox.test.ts
Labels: enhancement

#1210 feat: adds getChannelUsersQuery method, bumps to @esri/arcgis-rest-port…
  package-lock.json
  package.json
  packages/common/src/discussions/utils.ts
  packages/common/src/search/_internal/portalSearchGroupMembers.ts
  packages/common/src/search/_internal/portalSearchUsers.ts
  packages/common/src/search/hubSearch.ts
  packages/common/src/search/serializeQueryForPortal.ts
  packages/common/src/search/types/IHubCatalog.ts
  packages/common/src/users/HubUsers.ts
  packages/common/test/discussions/utils.test.ts
  packages/common/test/search/_internal/portalSearchUsers.test.ts
  packages/common/test/search/serializeQueryForPortal.test.ts
  packages/common/test/users/HubUsers.test.ts
  packages/downloads/package.json
Labels: Draft
