Repository Esri/hub.js, pull requests merged in 2024-10, with the labels that each got.

#1662 feat: scaffold catalog configuration experience
  packages/common/src/core/schemas/shared/CatalogSchema.ts
  packages/common/src/core/schemas/shared/index.ts
  packages/common/src/search/types/IHubCatalog.ts
  packages/common/src/types.ts
Labels: Draft

#1680 feat: switch scheduler to select format
  packages/common/src/content/_internal/ContentUiSchemaSettings.ts
  packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts
Labels: enhancement

#1684 feat(hub-common): add location props
  packages/common/src/core/schemas/shared/subschemas.ts
  packages/common/src/core/types/IHubLocation.ts
  packages/common/src/events/_internal/EventSchemaEdit.ts
  packages/common/src/events/_internal/EventUiSchemaEdit.ts
  packages/common/src/events/_internal/PropertyMapper.ts
  packages/common/src/events/_internal/getLocationFromEvent.ts
  packages/common/test/events/_internal/EventSchemaEdit.test.ts
  packages/common/test/events/_internal/EventUiSchemaEdit.test.ts
  packages/common/test/events/_internal/getLocationFromEvent.test.ts
  packages/common/test/events/edit.test.ts
Labels: Draft

#1686 feat(hub-discussions): add ChannelFilter to filter channels by disc uri
  packages/common/src/discussions/api/types.ts
Labels: Stale
