Repository Esri/hub.js, pull requests merged in 2024-11, with the labels that each got.

#1691 feat(): add create form error validation for site and project entities
  packages/common/src/core/schemas/shared/subschemas.ts
  packages/common/src/discussions/_internal/DiscussionUiSchemaCreate.ts
  packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts
  packages/common/src/groups/_internal/GroupUiSchemaCreate.ts
  packages/common/src/groups/_internal/GroupUiSchemaCreateAssociation.ts
  packages/common/src/groups/_internal/GroupUiSchemaCreateEdit.ts
  packages/common/src/groups/_internal/GroupUiSchemaCreateFollowers.ts
  packages/common/src/groups/_internal/GroupUiSchemaCreateView.ts
  packages/common/src/groups/_internal/GroupUiSchemaEdit.ts
  packages/common/src/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.ts
  packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate.ts
  packages/common/src/initiatives/_internal/InitiativeUiSchemaCreate2.ts
  packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts
  packages/common/src/pages/_internal/PageUiSchemaCreate.ts
  packages/common/src/pages/_internal/PageUiSchemaEdit.ts
  packages/common/src/projects/_internal/ProjectUiSchemaCreate.ts
  packages/common/src/projects/_internal/ProjectUiSchemaCreate2.ts
  packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
  packages/common/src/sites/_internal/SiteSchema.ts
  packages/common/src/sites/_internal/SiteUiSchemaCreate.ts
  packages/common/src/sites/_internal/SiteUiSchemaEdit.ts
  packages/common/src/surveys/_internal/SurveyUiSchemaEdit.ts
  packages/common/src/templates/_internal/TemplateUiSchemaEdit.ts
  packages/common/test/discussions/_internal/DiscussionUiSchemaCreate.test.ts
  packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaCreate.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaCreateAssociation.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaCreateEdit.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaCreateFollowers.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaCreateView.test.ts
  packages/common/test/groups/_internal/GroupUiSchemaEdit.test.ts
  packages/common/test/initiative-templates/_internal/InitiativeTemplateUiSchemaEdit.test.ts
  packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate.test.ts
  packages/common/test/initiatives/_internal/InitiativeUiSchemaCreate2.test.ts
  packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
  packages/common/test/pages/_internal/PageUiSchemaCreate.test.ts
  packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts
  packages/common/test/projects/_internal/ProjectUiSchemaCreate.test.ts
  packages/common/test/projects/_internal/ProjectUiSchemaCreate2.test.ts
  packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
  packages/common/test/sites/_internal/SiteUiSchemaCreate.test.ts
  packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts
  packages/common/test/surveys/_internal/SurveyUiSchemaEdit.test.ts
  packages/common/test/templates/_internal/TemplateUiSchemaEdit.test.ts
Labels: Draft

#1711 fix(): add notice to uiSchemas
  packages/common/src/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.ts
  packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts
  packages/common/test/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.test.ts
  packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts
Labels: Draft

#1717 fix(): expose editor to metric functions
  packages/common/src/core/schemas/internal/metrics/InitiativeUiSchemaMetrics.ts
  packages/common/src/core/schemas/internal/metrics/ProjectUiSchemaMetrics.ts
  packages/common/src/initiatives/HubInitiative.ts
  packages/common/src/initiatives/HubInitiatives.ts
  packages/common/src/metrics/editorToMetric.ts
  packages/common/src/metrics/index.ts
  packages/common/src/metrics/metricToEditor.ts
  packages/common/src/projects/HubProject.ts
  packages/common/src/projects/edit.ts
  packages/common/test/core/schemas/internal/metrics/ProjectUiSchemaMetrics.test.ts
  packages/common/test/initiatives/HubInitiative.test.ts
  packages/common/test/initiatives/HubInitiatives.test.ts
  packages/common/test/metrics/editorToMetric.test.ts
  packages/common/test/metrics/metricToEditor.test.ts
  packages/common/test/projects/edit.test.ts
Labels: Stale

#1720 feat: expose item size for content entities
  packages/common/src/content/_internal/getPropertyMap.ts
  packages/common/src/core/types/IHubItemEntity.ts
Labels: enhancement, Stale

#1733 feat(): add executed query length to search response
  packages/common/src/search/_internal/portalSearchGroups.ts
  packages/common/src/search/_internal/portalSearchItems.ts
  packages/common/src/search/_internal/portalSearchUsers.ts
  packages/common/src/search/explainQueryResult.ts
  packages/common/src/search/types/IHubSearchResponse.ts
  packages/common/src/search/types/types.ts
  packages/common/src/search/utils.ts
  packages/common/test/search/utils.test.ts
Labels: Stale

#1707 feat(): add link org settings in user workspace
  package-lock.json
  packages/common/src/users/_internal/UserUiSchemaSettings.ts
  packages/common/src/users/_internal/computeProps.ts
  packages/common/test/users/_internal/UserUiSchemaSettings.test.ts
  packages/common/test/users/_internal/computeProps.test.ts
Labels: Draft
