Repository Esri/hub.js, pull requests merged in 2024-05, with the labels that each got.

#1483 feat(): remove default groups
  packages/common/src/core/types/HubEntityEditor.ts
  packages/common/src/initiatives/HubInitiative.ts
  packages/common/src/projects/HubProject.ts
  packages/common/test/initiatives/HubInitiative.test.ts
  packages/common/test/projects/HubProject.test.ts
Labels: Stale

#1494 feat: scheduler force update
  packages/common/src/content/_internal/ContentSchema.ts
  packages/common/src/content/_internal/ContentUiSchemaSettings.ts
  packages/common/src/content/_internal/getSchedulerApiUrl.ts
  packages/common/src/content/_internal/internalContentUtils.ts
  packages/common/src/content/edit.ts
  packages/common/src/content/manageSchedule.ts
  packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts
  packages/common/test/content/edit.test.ts
  packages/common/test/content/manageSchedule.test.ts
Labels: enhancement

#1492 fix: updates well known types to fix gallery query
  package-lock.json
  packages/common/src/search/_internal/portalSearchItems.ts
Labels: Draft

#1500 feat(hub-common): removes hub:feature:gallery:map permission policy
  packages/common/src/permissions/HubPermissionPolicies.ts
  packages/common/src/permissions/types/Permission.ts
Labels: Draft

#1533 refactor: flatten and nested categories
  packages/common/src/content/_internal/ContentUiSchemaEdit.ts
  packages/common/src/core/schemas/internal/getCategoryItems.ts
  packages/common/src/core/schemas/types.ts
  packages/common/src/discussions/_internal/DiscussionUiSchemaEdit.ts
  packages/common/src/events/_internal/EventUiSchemaEdit.ts
  packages/common/src/initiatives/_internal/InitiativeUiSchemaEdit.ts
  packages/common/src/pages/_internal/PageUiSchemaEdit.ts
  packages/common/src/projects/_internal/ProjectUiSchemaEdit.ts
  packages/common/src/sites/_internal/SiteUiSchemaEdit.ts
  packages/common/src/surveys/_internal/SurveyUiSchemaEdit.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/isComboboxItemSelected.ts
  packages/common/test/content/_internal/ContentUiSchemaEdit.test.ts
  packages/common/test/core/schemas/internal/getCategoryItems.test.ts
  packages/common/test/discussions/_internal/DiscussionUiSchemaEdit.test.ts
  packages/common/test/events/_internal/EventUiSchemaEdit.test.ts
  packages/common/test/initiatives/_internal/InitiativeUiSchemaEdit.test.ts
  packages/common/test/pages/_internal/PageUiSchemaEdit.test.ts
  packages/common/test/projects/_internal/ProjectUiSchemaEdit.test.ts
  packages/common/test/sites/_internal/SiteUiSchemaEdit.test.ts
  packages/common/test/surveys/_internal/SurveyUiSchemaEdit.test.ts
  packages/common/test/utils/isComboboxItemSelected.test.ts
Labels: bug, refactor
