Repository Esri/hub.js, pull requests merged in 2024-04, with the labels that each got.

#1465 feat: added permission for download errors
  packages/common/src/content/_internal/ContentBusinessRules.ts
Labels: enhancement

#1460 feat(): enrich initiatives with correct links
  packages/common/src/content/_internal/internalContentUtils.ts
  packages/common/src/initiatives/HubInitiatives.ts
  packages/common/src/initiatives/_internal/computeLinks.ts
  packages/common/src/search/_internal/portalSearchItems.ts
  packages/common/test/content/content.test.ts
  packages/common/test/initiatives/HubInitiatives.test.ts
  packages/common/test/initiatives/_internal/computeLinks.test.ts
Labels: Stale

#1471 feat: scheduler added to content uischema
  packages/common/src/content/_internal/ContentBusinessRules.ts
  packages/common/src/content/_internal/ContentSchema.ts
  packages/common/src/content/_internal/ContentUiSchemaSettings.ts
  packages/common/src/content/_internal/computeProps.ts
  packages/common/src/content/edit.ts
  packages/common/src/content/fetch.ts
  packages/common/src/content/manageSchedule.ts
  packages/common/src/core/types/IHubEditableContent.ts
  packages/common/src/core/types/IHubSchedule.ts
  packages/common/src/items/_enrichments.ts
  packages/common/test/content/_internal/ContentUiSchemaSettings.test.ts
  packages/common/test/content/edit.test.ts
  packages/common/test/content/fetch.test.ts
  packages/common/test/content/manageSchedule.test.ts
  packages/common/test/mocks/mock-auth.ts
Labels: enhancement

#1478 fix: proper export path for schedule interfaces
  packages/common/src/core/types/index.ts
Labels: chore

#1480 fix(hub-common): add startDate, startTime, endDate, endTime to create…
  packages/common/src/events/api/orval/api/orval-events.ts
  packages/common/src/events/edit.ts
  packages/common/test/events/api/events.test.ts
  packages/common/test/events/edit.test.ts
Labels: Stale
