Repository Esri/hub.js, pull requests merged in 2024-12, with the labels that each got.

#1760 fix(): add required type to IChangeEventDetail
  packages/common/src/core/schemas/types.ts
  packages/common/src/sites/_internal/SiteUiSchemaSettings.ts
  packages/common/test/sites/_internal/SiteuUiSchemaSettings.test.ts
Labels: Stale

#1764 fix: removing extra launch icons on user settings
  package-lock.json
  packages/common/src/users/_internal/UserUiSchemaSettings.ts
  packages/common/test/users/_internal/UserUiSchemaSettings.test.ts
Labels: bug

#1726 feat(): handle item type combobox with nested selections
  packages/common/src/search/_internal/portalSearchItems.ts
  packages/common/src/types.ts
  packages/common/src/utils/isComboboxItemSelected.ts
  packages/common/test/search/_internal/portalSearchItems.test.ts
  packages/common/test/utils/isComboboxItemSelected.test.ts
Labels: Draft

#1768 fix(): add catalog permission
  packages/common/src/initiatives/_internal/InitiativeBusinessRules.ts
  packages/common/src/projects/_internal/ProjectBusinessRules.ts
Labels: Stale
